// Generates supabase/seed.sql from seed/seed.json (extracted from the supplied source files).
import { readFileSync, writeFileSync } from "node:fs";

const seed = JSON.parse(readFileSync(new URL("../seed/seed.json", import.meta.url), "utf8"));
const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const first = (n) => n.split(" ")[0];
const out = [];
const add = (s) => out.push(s);

add("-- Generated by scripts/generate-seed.mjs from seed/seed.json. Do not edit by hand.");
add("insert into public.roles (name, description) values");
add(
  [
    ["team_member", "Works on assigned processes"],
    ["production_lead", "Leads a team; manages status through Review"],
    ["reviewer", "Records review decisions and approves review-point closure"],
    ["supporting_role", "Supporting assignment (front office, auditor communication, payments)"],
    ["project_lead", "Views all processes; controls Production"],
    ["dashboard_lead", "Controls the countdown and the Production build status"],
    ["project_head", "Management dashboard"],
    ["system_admin", "Manages users, roles, teams and assignments"],
  ]
    .map(([n, d]) => `  (${q(n)}, ${q(d)})`)
    .join(",\n") + ";",
);

add("insert into public.people (display_name, first_name) values");
add(seed.people.map((n) => `  (${q(n)}, ${q(first(n))})`).join(",\n") + ";");

const globals = [
  ["Shon J Iype", "project_head"],
  ["Shon Domnic", "project_lead"],
  ["Jibin K K", "dashboard_lead"],
  ["Jibin K K", "system_admin"],
];
add("insert into public.person_roles (person_id, role_id)");
add(
  "select p.id, r.id from (values " +
    globals.map(([p, r]) => `(${q(p)}, ${q(r)})`).join(", ") +
    ") v(person, role) join public.people p on p.display_name = v.person join public.roles r on r.name = v.role;",
);

add("insert into public.phases (name, display_order) values");
add(seed.phases.map((n, i) => `  (${q(n)}, ${i + 1})`).join(",\n") + ";");

for (const p of seed.processes) {
  add(
    `insert into public.processes (process_code, title, phase_id, source_reference, context) select ${q(p.code)}, ${q(p.title)}, id, ${q(p.source_reference)}, ${q(JSON.stringify(p.context))}::jsonb from public.phases where name = ${q(p.phase)};`,
  );
  add(
    "insert into public.subprocesses (process_id, seq, title) select id, v.seq, v.title from public.processes, (values " +
      p.subprocesses.map((s) => `(${s.seq}, ${q(s.title)})`).join(", ") +
      `) v(seq, title) where process_code = ${q(p.code)};`,
  );
  const rows = [
    [p.production_lead, "production_lead"],
    ...p.team_members.map((n) => [n, "team_member"]),
    ...p.reviewers.map((n) => [n, "reviewer"]),
    ...p.supporting.map((n) => [n, "supporting_role"]),
  ];
  add(
    "insert into public.process_assignments (process_id, person_id, assignment_type) select pr.id, pe.id, v.t::public.assignment_type from public.processes pr, (values " +
      rows.map(([n, t]) => `(${q(n)}, ${q(t)})`).join(", ") +
      `) v(name, t) join public.people pe on pe.display_name = v.name where pr.process_code = ${q(p.code)};`,
  );
}

// Teams as drawn on the team-structure page.
const teams = {
  Pavithra: [
    "Rijin",
    "Anna",
    "Neeraja",
    "Hiba",
    "Devika T G",
    "Ashly",
    "Ananthakrishan",
    "Jeffin",
    "Darly",
    "Ramees",
    "Cini",
    "Sandhya",
    "Bisnu",
  ],
  Rustham: [
    "Ajay",
    "Elizabeth",
    "Jewel",
    "Vineetha",
    "Aswathy",
    "Liya",
    "Nihal",
    "Deepak",
    "Arnold",
    "Athira",
    "Sreenanda",
    "Emanuval",
    "Maria",
  ],
};
for (const [lead, members] of Object.entries(teams)) {
  add(
    `insert into public.teams (name, production_lead_person_id) select ${q("Team " + lead)}, id from public.people where display_name = ${q(lead)};`,
  );
  add(
    "insert into public.team_members (team_id, person_id) select t.id, p.id from public.teams t, public.people p where t.name = " +
      q("Team " + lead) +
      " and p.display_name in (" +
      members.map(q).join(", ") +
      ");",
  );
}

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n") + "\n");
console.log("wrote supabase/seed.sql");
